[package]
name = "fahrenhelsius"
version = "0.1.0"
authors = ["Marushkevych <marushkevych@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_utils = { path = "../rust_utils" }